latitude: "37.311395°"
longitude: "127.085556°"

# secrets.yaml
wifi_ssid_office: "iptime-kk"
wifi_password_office: "k2k2k2k2"

wifi_ssid_home: "SK_WiFiGIGA8B68_2.4G"
wifi_password_home: "AAD99@9197"

wifi_ssid_nongmak: "U+Net4CE7"
wifi_password_nongmak: "32F5013301"

api_encryption_key: "BoCCG/J+KiX8AMqrGllPk1DXbUHgR/Ivbj5+w9ZZiII="
ota_password: "rpahbed6"
fallback_ap_password: "rpahbed6"
